---
- name: Get target node info
  package_facts:
    manager: auto

- name: Extract list of packages
  set_fact:
    target_packages: "{{ ansible_facts.packages.keys() }}"

- name: Check for unwanted packages
  set_fact:
    packages_delta: "{{ target_packages | intersect(csi_services_list) }}"

- name: Audit result
  debug:
    msg: "Found {{ packages_delta | length }} package(s): {{ packages_delta }}"
  failed_when: packages_delta | length > 0
  ignore_errors: true