---
- name: MTA remediation
  include_tasks: mta_remediation.yaml
  when: mta_remediation

- name: Soft remediation # uninstall and mask services
  include_tasks: remediation_soft.yaml
  when: not remediation_hard

- name: Hard remediation # uninstall all
  include_tasks: remediation_hard.yaml
  when: remediation_hard
