---
- name: MTA remediation
  include_tasks: mta_remediation.yaml
  when: mta_remediation

  # uninstall packages and mask services
- name: Soft remediation
  include_tasks: remediation_soft.yaml
  when: not remediation_hard
  
  # uninstall all packages
- name: Hard remediation
  include_tasks: remediation_hard.yaml
  when: remediation_hard
