---
- name: Check packages
  import_tasks: packages_check.yaml

- name: Check MTA
  import_tasks: mta_check.yaml

- name: Check services masks
  include_tasks: masks_check.yaml
  loop: "{{ csi_maskable_services }}"

- name: Show audit summary
  import_tasks: audit_summary.yaml